import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Rethink_Sans } from "next/font/google";
import "./globals.css";

const Rethink = Rethink_Sans({ subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter', 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${Rethink.className} ${geistMono.variable} bg-lamaLight min-h-screen flex flex-col`}
      >
        {children}
      </body>
    </html>
  );
}
